name: Test before merging to Development and Main

on:
  push:
    branches: [main, development]
  pull_request:
    branches: [main, development]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master

      - name: Setup Node.js environment and run test
        uses: actions/setup-node@v2.1.5

      - name: Install Dependencies
        run: npm install

      - name: Run Test
        run: npm run test -- --configuration=ci
