name: Test before merging to Development and Main

on:
  push:
    branches: [ main, development ]
  pull_request:
    branches: [ main, development ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    
    - uses: actions/setup-node@v2.1.5
    - name: Setup Node.js environment and run test
      run: npm run test
